[2024-11-18T21:12:26.810+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T21:12:26.825+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_a.sum_results manual__2024-11-18T16:12:13.891274+00:00 [queued]>
[2024-11-18T21:12:26.834+0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_a.sum_results manual__2024-11-18T16:12:13.891274+00:00 [queued]>
[2024-11-18T21:12:26.835+0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-18T21:12:26.855+0500] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): sum_results> on 2024-11-18 16:12:13.891274+00:00
[2024-11-18T21:12:26.862+0500] {standard_task_runner.py:72} INFO - Started process 21522 to run task
[2024-11-18T21:12:26.865+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'count_a', 'sum_results', 'manual__2024-11-18T16:12:13.891274+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_1.py', '--cfg-path', '/tmp/tmpda1z5_3w']
[2024-11-18T21:12:26.867+0500] {standard_task_runner.py:105} INFO - Job 13: Subtask sum_results
[2024-11-18T21:12:26.917+0500] {task_command.py:467} INFO - Running <TaskInstance: count_a.sum_results manual__2024-11-18T16:12:13.891274+00:00 [running]> on host archlinux
[2024-11-18T21:12:27.013+0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_a' AIRFLOW_CTX_TASK_ID='sum_results' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T16:12:13.891274+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T16:12:13.891274+00:00'
[2024-11-18T21:12:27.014+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T21:12:27.015+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T21:12:27.015+0500] {logging_mixin.py:190} INFO - Current task name:sum_results state:running start_date:2024-11-18 16:12:26.826037+00:00
[2024-11-18T21:12:27.015+0500] {logging_mixin.py:190} INFO - Dag name:count_a and current dag run status:running
[2024-11-18T21:12:27.015+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T21:12:27.023+0500] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/dags/dag_1.py", line 43, in sum_results
    with open('result.txt', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'result.txt'
[2024-11-18T21:12:27.036+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-18T21:12:27.036+0500] {logging_mixin.py:190} INFO - Task start:2024-11-18 16:12:26.826037+00:00 end:2024-11-18 16:12:27.035280+00:00 duration:0.209243
[2024-11-18T21:12:27.036+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): sum_results> dag:<DAG: count_a> dagrun:<DagRun count_a @ 2024-11-18 16:12:13.891274+00:00: manual__2024-11-18T16:12:13.891274+00:00, state:running, queued_at: 2024-11-18 16:12:13.909806+00:00. externally triggered: True>
[2024-11-18T21:12:27.037+0500] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Permission denied: 'result.txt'
[2024-11-18T21:12:27.037+0500] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=count_a, task_id=sum_results, run_id=manual__2024-11-18T16:12:13.891274+00:00, execution_date=20241118T161213, start_date=20241118T161226, end_date=20241118T161227
[2024-11-18T21:12:27.057+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T21:12:27.057+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task sum_results ([Errno 13] Permission denied: 'result.txt'; 21522)
Traceback (most recent call last):
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/AtlasRise/airflow/dags/dag_1.py", line 43, in sum_results
    with open('result.txt', 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'result.txt'
[2024-11-18T21:12:27.079+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-18T21:12:27.102+0500] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T21:12:27.103+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
